# Copyright (c) 2025 Mimi Zohar <zohar@linux.ibm.com>

name: checkpatch review
on: [push, pull_request]
jobs:
  review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: run checkpatch
      id: run_checkpatch
      run: |
        if [ ${{ github.event_name }} == 'pull_request' ]; then
          echo "checkpatch event: pull_request"
          count=$(git rev-list --count ${{ github.base_ref }}..${{ github.head_ref }} )
          echo "count $count"
          git format-patch -$count ${{ github.head_ref }} -o patches/
        else
          echo "checkpatch event: ${{ github.event_name }} forced: ${{ github.event.forced }}"
          for commit in ${{ join(github.event.commits.*.id, ' ') }}; do
              git format-patch -1 $commit -o patches/
          done
        fi
        scripts/checkpatch.pl patches/*  --strict --terse  --no-tree --ignore CONST_STRUCT,VOLATILE,SPLIT_STRING,FILE_PATH_CHANGES
